name: CI Pipeline

on: [push, pull_request]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install mypy

    - name: Install charset_normalizer
      run: pip install charset_normalizer

    - name: Ensure Fortran sources are UTF-8 encoded
      run: |
        find fortran -name '*.f90' -exec bash -c 'iconv -f $(file -bi "$1" | sed "s/.*[ ]charset=//") -t utf-8 "$1" -o "$1"' _ {} \;

    - name: Lint with flake8
      run: |
        pip install flake8
        flake8 opt_fuel

    - name: Type-check with mypy
      run: mypy opt_fuel

    - name: Run tests with pytest
      run: pytest
