name: Fortran CI Pipeline

on: [push, pull_request]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y gfortran python3-pip

    - name: Install Python packages
      run: pip install numpy

    - name: Compile Fortran modules with f2py
      run: |
        f2py -c -m emissions fortran/calculate_emissions.f90
        f2py -c -m efficiency fortran/optimize_fuel_efficiency.f90
        f2py -c -m tradeoffs fortran/analyze_trade_offs.f90

    - name: Run Python tests (add your test script)
      run: python3 tests/run_tests.py
